package com.elpepe.uhc.item;

import com.elpepe.uhc.Uhc;
import com.elpepe.uhc.entity.ModEntities;
import com.elpepe.uhc.item.armor.EffectArmor;
import com.elpepe.uhc.item.armor.ModArmorMaterials;
import com.elpepe.uhc.item.armor.custom.AirtagItem;
import com.elpepe.uhc.item.armor.custom.DeathrunLeggings;
import com.elpepe.uhc.item.armor.custom.MagmaBoots;
import com.elpepe.uhc.item.armor.custom.NightVisionHelmetItem;
import com.elpepe.uhc.item.armor.custom.PoseidonHelmet;
import com.elpepe.uhc.item.armor.custom.SlimeBoots;
import com.elpepe.uhc.item.food.GlowBerriesJam;
import com.elpepe.uhc.item.food.JamFood;
import com.elpepe.uhc.item.food.ModFoodComponents;
import com.elpepe.uhc.item.food.RavagerMeat;
import com.elpepe.uhc.item.other.CastIronCauldronBlockItem;
import com.elpepe.uhc.item.other.DragonHeart;
import com.elpepe.uhc.item.other.HealthJar;
import com.elpepe.uhc.item.other.RadarItem;
import com.elpepe.uhc.item.tool.HarpoonItem;
import com.elpepe.uhc.item.tool.ModToolMaterial;
import com.elpepe.uhc.item.weapon.LavaSword;
import com.elpepe.uhc.item.weapon.SharpEmeraldSword;
import java.util.List;
import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.minecraft.util.Formatting;
import net.minecraft.entity.effect.StatusEffects;
import net.minecraft.item.ArmorItem;
import net.minecraft.item.AxeItem;
import net.minecraft.item.StewItem;
import net.minecraft.item.Item;
import net.minecraft.item.HoeItem;
import net.minecraft.item.PickaxeItem;
import net.minecraft.item.ShovelItem;
import net.minecraft.item.SpawnEggItem;
import net.minecraft.item.SwordItem;
import net.minecraft.registry.Registry;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;
import net.minecraft.registry.Registries;
import net.minecraft.item.SmithingTemplateItem;
import net.minecraft.item.ArmorItem.class_8051;

public class ModItems {
   public static final List<Identifier> armorTrimEmptyBaseSlotTextures = List.of(new Identifier("item/empty_armor_slot_helmet"), new Identifier("item/empty_armor_slot_chestplate"), new Identifier("item/empty_armor_slot_leggings"), new Identifier("item/empty_armor_slot_boots"));
   public static final List<Identifier> armorTrimEmptyAdditionsSlotTextures = List.of(new Identifier("item/empty_slot_ingot"), new Identifier("item/empty_slot_redstone_dust"), new Identifier("item/empty_slot_quartz"), new Identifier("item/empty_slot_emerald"), new Identifier("item/empty_slot_diamond"), new Identifier("item/empty_slot_lapis_lazuli"), new Identifier("item/empty_slot_amethyst_shard"));
   public static final Text APPLIES_TO;
   public static final Text INGREDIENTS;
   public static final Text BASE_SLOT_DESC;
   public static final Text ADDITIONS_SLOT_DESC;
   public static final Formatting DESC_FORMATTING;
   public static final Item RAW_NITHRIL;
   public static final Item NITHRIL_INGOT;
   public static final Item NITHRIL_PLATE;
   public static final Item RUBY;
   public static final Item SHARP_STONE;
   public static final Item BLOODY_JAR;
   public static final Item HEALTH_JAR;
   public static final Item RUBY_TOTEM;
   public static final Item RADAR;
   public static final Item DRAGON_HEART;
   public static final Item HARPOON;
   public static final Item LAVA_SWORD;
   public static final Item EMERALD_SWORD;
   public static final Item SHARP_EMERALD_SWORD;
   public static final Item DRAGON_PICKAXE;
   public static final Item NETHERITE_COVERED_DRAGON_PICKAXE;
   public static final Item NIGHT_VISION_HELMET;
   public static final Item AIRTAG;
   public static final Item POSEIDON_HELMET;
   public static final Item FEATHER_BOOTS;
   public static final Item SLIME_BOOTS;
   public static final Item DEATHRUN_LEGGINGS;
   public static final Item MAGMA_BOOTS;
   public static final Item SWEET_BERRIES_JAM;
   public static final Item GLOW_BERRIES_JAM;
   public static final Item POISONOUS_SOUP;
   public static final Item SEAFOOD_SOUP;
   public static final Item GOAT_MEAT;
   public static final Item COOKED_GOAT_MEAT;
   public static final Item HORSE_LIKE_MEAT;
   public static final Item COOKED_HORSE_LIKE_MEAT;
   public static final Item LLAMA_MEAT;
   public static final Item COOKED_LLAMA_MEAT;
   public static final Item RAVAGER_MEAT;
   public static final Item COOKED_RAVAGER_MEAT;
   public static final Item CAST_IRON_CAULDRON_BLOCK_ITEM;
   public static final Item EARTHQUAKE_ARMOR_TRIM_SMITHING_TEMPLATE;
   public static final Item GOBLIN_SPAWN_EGG;
   public static final Item MYSTERIOUS_TRADER_SPAWN_EGG;
   public static final Item NITHRIL_HELMET;
   public static final Item NITHRIL_CHESTPLATE;
   public static final Item NITHRIL_LEGGINGS;
   public static final Item NITHRIL_BOOTS;
   public static final Item NITHRIL_SWORD;
   public static final Item NITHRIL_PICKAXE;
   public static final Item NITHRIL_AXE;
   public static final Item NITHRIL_SHOVEL;
   public static final Item NITHRIL_HOE;

   private static Item registerItem(String name, Item item) {
      return (Item)Registry.register(Registries.ITEM, new Identifier(Uhc.MOD_ID, name), item);
   }

   public static void registerModItems() {
      Uhc.LOGGER.info("Registering Mod Items for " + Uhc.MOD_ID);
   }

   static {
      APPLIES_TO = Text.translatable("item.minecraft.smithing_template.armor_trim.applies_to").formatted(Formatting.BLUE);
      INGREDIENTS = Text.translatable("item.minecraft.smithing_template.armor_trim.ingredients").formatted(Formatting.BLUE);
      BASE_SLOT_DESC = Text.translatable("item.minecraft.smithing_template.armor_trim.base_slot_description");
      ADDITIONS_SLOT_DESC = Text.translatable("item.minecraft.smithing_template.armor_trim.additions_slot_description");
      DESC_FORMATTING = Formatting.GRAY;
      RAW_NITHRIL = registerItem("raw_nithril", new Item(new FabricItemSettings()));
      NITHRIL_INGOT = registerItem("nithril_ingot", new Item(new FabricItemSettings()));
      NITHRIL_PLATE = registerItem("nithril_plate", new Item(new FabricItemSettings()));
      RUBY = registerItem("ruby", new Item(new FabricItemSettings()));
      SHARP_STONE = registerItem("stone_of_sharpness", new Item((new FabricItemSettings()).maxCount(1)));
      BLOODY_JAR = registerItem("bloody_jar", new Item((new FabricItemSettings()).maxCount(16)));
      HEALTH_JAR = registerItem("health_jar", new HealthJar((new FabricItemSettings()).maxCount(1)));
      RUBY_TOTEM = registerItem("ruby_totem", new Item((new FabricItemSettings()).maxCount(1).maxDamage(2)));
      RADAR = registerItem("radar", new RadarItem((new FabricItemSettings()).maxCount(1).maxDamage(3)));
      DRAGON_HEART = registerItem("dragon_heart", new DragonHeart((new FabricItemSettings()).maxDamage(1)));
      HARPOON = registerItem("harpoon", new HarpoonItem((new FabricItemSettings()).maxCount(1)));
      LAVA_SWORD = registerItem("lava_sword", new LavaSword(ModToolMaterial.LAVA, 0, -2.4F, new FabricItemSettings()));
      EMERALD_SWORD = registerItem("emerald_sword", new SwordItem(ModToolMaterial.EMERALD, 0, -2.3F, new FabricItemSettings()));
      SHARP_EMERALD_SWORD = registerItem("sharp_emerald_sword", new SharpEmeraldSword(ModToolMaterial.EMERALD, 4, -2.3F, new FabricItemSettings()));
      DRAGON_PICKAXE = registerItem("dragon_pickaxe", new PickaxeItem(ModToolMaterial.DRAGON, -1, -2.8F, new FabricItemSettings()));
      NETHERITE_COVERED_DRAGON_PICKAXE = registerItem("netherite_covered_dragon_pickaxe", new PickaxeItem(ModToolMaterial.DRAGON, -1, -2.8F, (new FabricItemSettings()).fireproof()));
      NIGHT_VISION_HELMET = registerItem("night_vision_helmet", (new NightVisionHelmetItem(ModArmorMaterials.NIGHT_VISION, class_8051.HELMET, new FabricItemSettings())).addArmorEffect(new EffectArmor.ArmorEffect(StatusEffects.NIGHT_VISION, 260, 0)));
      AIRTAG = registerItem("airtag", new AirtagItem(ModArmorMaterials.AIRTAG, class_8051.HELMET, new FabricItemSettings()));
      POSEIDON_HELMET = registerItem("poseidon_helmet", new PoseidonHelmet(ModArmorMaterials.POSEIDON, class_8051.HELMET, new FabricItemSettings()));
      FEATHER_BOOTS = registerItem("feather_boots", (new EffectArmor(ModArmorMaterials.FEATHER, class_8051.BOOTS, new FabricItemSettings())).addArmorEffect(StatusEffects.SLOW_FALLING, 1).addTooltip("tooltip.uhc.feather_boots"));
      SLIME_BOOTS = registerItem("slime_boots", (new SlimeBoots(ModArmorMaterials.SLIME, class_8051.BOOTS, new FabricItemSettings())).addArmorEffect(StatusEffects.JUMP_BOOST, 3).addTooltip("tooltip.uhc.slime_boots"));
      DEATHRUN_LEGGINGS = registerItem("deathrun_leggings", new DeathrunLeggings(ModArmorMaterials.DEATHRUN, class_8051.LEGGINGS, new FabricItemSettings()));
      MAGMA_BOOTS = registerItem("magma_boots", new MagmaBoots(ModArmorMaterials.MAGMA, class_8051.BOOTS, new FabricItemSettings()));
      SWEET_BERRIES_JAM = registerItem("sweet_berries_jam", new JamFood((new FabricItemSettings()).maxCount(4).food(ModFoodComponents.SWEET_BERRIES_JAM)));
      GLOW_BERRIES_JAM = registerItem("glow_berries_jam", new GlowBerriesJam((new FabricItemSettings()).maxCount(4).food(ModFoodComponents.GLOW_BERRIES_JAM)));
      POISONOUS_SOUP = registerItem("poisonous_soup", new StewItem((new FabricItemSettings()).maxCount(4).food(ModFoodComponents.POISONOUS_SOUP)));
      SEAFOOD_SOUP = registerItem("seafood_soup", new StewItem((new FabricItemSettings()).maxCount(4).food(ModFoodComponents.SEAFOOD_SOUP)));
      GOAT_MEAT = registerItem("goat_meat", new Item((new FabricItemSettings()).food(ModFoodComponents.GOAT_MEAT)));
      COOKED_GOAT_MEAT = registerItem("cooked_goat_meat", new Item((new FabricItemSettings()).food(ModFoodComponents.COOKED_GOAT_MEAT)));
      HORSE_LIKE_MEAT = registerItem("horse_like_meat", new Item((new FabricItemSettings()).food(ModFoodComponents.HORSE_LIKE_MEAT)));
      COOKED_HORSE_LIKE_MEAT = registerItem("cooked_horse_like_meat", new Item((new FabricItemSettings()).food(ModFoodComponents.COOKED_HORSE_LIKE_MEAT)));
      LLAMA_MEAT = registerItem("llama_meat", new Item((new FabricItemSettings()).food(ModFoodComponents.LLAMA_MEAT)));
      COOKED_LLAMA_MEAT = registerItem("cooked_llama_meat", new Item((new FabricItemSettings()).food(ModFoodComponents.COOKED_LLAMA_MEAT)));
      RAVAGER_MEAT = registerItem("ravager_meat", new RavagerMeat((new FabricItemSettings()).food(ModFoodComponents.RAVAGER_MEAT)));
      COOKED_RAVAGER_MEAT = registerItem("cooked_ravager_meat", new RavagerMeat((new FabricItemSettings()).food(ModFoodComponents.COOKED_RAVAGER_MEAT)));
      CAST_IRON_CAULDRON_BLOCK_ITEM = registerItem("cast_iron_cauldron", new CastIronCauldronBlockItem(new FabricItemSettings(), 2.0F));
      EARTHQUAKE_ARMOR_TRIM_SMITHING_TEMPLATE = registerItem("earthquake_armor_trim_smithing_template", new SmithingTemplateItem(APPLIES_TO, INGREDIENTS, Text.translatable("trim_pattern.uhc.earthquake").formatted(DESC_FORMATTING), BASE_SLOT_DESC, ADDITIONS_SLOT_DESC, armorTrimEmptyBaseSlotTextures, armorTrimEmptyAdditionsSlotTextures));
      GOBLIN_SPAWN_EGG = registerItem("goblin_spawn_egg", new SpawnEggItem(ModEntities.GOBLIN_ENTITY, 4762932, 13825987, new FabricItemSettings()));
      MYSTERIOUS_TRADER_SPAWN_EGG = registerItem("mysterious_trader_spawn_egg", new SpawnEggItem(ModEntities.MYSTERIOUS_TRADER, 14358031, 11347203, new FabricItemSettings()));
      NITHRIL_HELMET = registerItem("nithril_helmet", new ArmorItem(ModArmorMaterials.NITHRIL, class_8051.HELMET, new FabricItemSettings()));
      NITHRIL_CHESTPLATE = registerItem("nithril_chestplate", new ArmorItem(ModArmorMaterials.NITHRIL, class_8051.CHESTPLATE, new FabricItemSettings()));
      NITHRIL_LEGGINGS = registerItem("nithril_leggings", new ArmorItem(ModArmorMaterials.NITHRIL, class_8051.LEGGINGS, new FabricItemSettings()));
      NITHRIL_BOOTS = registerItem("nithril_boots", new ArmorItem(ModArmorMaterials.NITHRIL, class_8051.BOOTS, new FabricItemSettings()));
      NITHRIL_SWORD = registerItem("nithril_sword", new SwordItem(ModToolMaterial.NITHRIL, 5, -2.4F, new FabricItemSettings()));
      NITHRIL_PICKAXE = registerItem("nithril_pickaxe", new PickaxeItem(ModToolMaterial.NITHRIL, 3, -2.8F, new FabricItemSettings()));
      NITHRIL_AXE = registerItem("nithril_axe", new AxeItem(ModToolMaterial.NITHRIL, 8.0F, -3.0F, new FabricItemSettings()));
      NITHRIL_SHOVEL = registerItem("nithril_shovel", new ShovelItem(ModToolMaterial.NITHRIL, 2.0F, -3.0F, new FabricItemSettings()));
      NITHRIL_HOE = registerItem("nithril_hoe", new HoeItem(ModToolMaterial.NITHRIL, -1, 0.0F, new FabricItemSettings()));
   }
}
